export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const ATTEMPT_LOGIN_SUCCESS = 'ATTEMPT_LOGIN_SUCCESS';
export const ATTEMPT_REGISTER = 'ATTEMPT_REGISTER';

export const ATTEMPT_LOGOUT_SUCCESS = 'ATTEMPT_LOGOUT_SUCCESS';


export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';