
export const ATTEMPT_LOGIN_SUCCESS = 'ATTEMPT_LOGIN_SUCCESS';
export const ATTEMPT_REGISTER_SUCCESS = 'ATTEMPT_REGISTER_SUCCESS';
export const ATTEMPT_LOGOUT_SUCCESS = 'ATTEMPT_LOGOUT_SUCCESS';

export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export const CREATE_GAME_SUCCEED = 'CREATE_GAME_SUCCEED';
export const PLAY_GAME_SUCCEED = 'PLAY_GAME_SUCCEED';

export const REMOVE_ALL_GAMES_SUCCEED = 'REMOVE_ALL_GAMES_SUCCEED';

export const RECREATE_GAME_LIST = 'RECREATE_GAME_LIST';

export const USER_PICK_SUCCEED = 'USER_PICK_SUCCEED';
